Remove confusing reset feature
teafuljs/teaful pull request #44
Opened 2021-11-12 20:56 UTC by aralroca

Fixes https://github.com/teafuljs/teaful/issues/41

Pre-released in `0.8.0-canary.1`. _(If you want to try it)_

Remove the "reset" as the responsibility of the library. In this way:

**Pros:**
- Removing confusion as to what exactly the reset function did. Simplifying and making it easier to understand.
- Fewer things in memory. Thus it is not necessary to save the store + initialStore. Only the store. This improves performance for applications with very large stores.
- Tiniest. Supporting reset made it take up more bits.
- Removing a feature that did not add value to the library, since the same could be done with the setter.
- More flexibility to the user to reset with the setter where the user wants: last value, last value fetched to an API, initial value...

**Cons:**
- The user will be responsible for controlling the reset. That is, save the value in memory.

    Example:
    ```js
    const [value, setValue] = useStore.value()
    const lastValue = useRef(value)

    // After some changes, is possible to reset with:
    setValue(lastValue.current)
    ```

    Another example:
    ```js
     const initialStore = { count: 0 }
     export const { getStore } = createStore(initialStore)
     const [,setStore] = getStore()

     export const reset = () => setStore(initialStore)
    ```
    ```js
     import { reset } from './store'

     function ResetStore() {
       return <button onClick={reset}>Reset store</button>
    }
    ```

2021-11-12 21:42 UTC, danielart requested changes
Could you change it on examples folder? I could manage that if you want in an other pr

2021-11-12 21:49 UTC, aralroca commented
An extra pro 🙂:

- `useStore` proxy hook now is more familiar with `React.useState`.

2021-11-12 22:10 UTC, danielart approved these changes

2021-11-13 06:12 UTC, yathink3 commented
It make more sense now

2021-11-14 10:19 UTC, merged